conversation_task:
  description: >
    Engage in natural conversation about {topic}.
    If it's a simple query (greeting, basic question):
      - Respond directly and naturally
    If it requires user context:
      - Check knowledge base first
    If it requires specific information:
      - Search the web only if needed
    Always:
      - Keep responses natural and concise
      - No meta-commentary or feedback requests
      - No showing of work process
  expected_output: >
    Natural conversational response
  agent: conversation_agent

knowledge_task:
  description: >
    Quickly retrieve relevant information from local knowledge when requested
  expected_output: >
    Concise, relevant information from knowledge base
  agent: knowledge_agent

search_task:
  description: >
    Search the web only when information isn't available locally
  expected_output: >
    Relevant web information when needed
  agent: search_agent

