analyze_query_task:
  description: >
    Analyze the user's query: "{topic}"
    Determine what type of response is needed:
    1. If it's a knowledge base query:
       - Questions about specific customers (e.g., names like "Olsen", "Smith", etc.)
       - Questions about customer details (phone, country, email, etc.)
       - Questions about products or documentation
    2. If it needs web search:
       - Current events or news
       - General information not about specific customers
       - Public information about companies or people
    3. If it's a coding question:
       - Technical questions
       - Programming related queries
    4. If it's just a normal conversation:
       - Greetings
       - General chit-chat
       - Opinion questions
    
    IMPORTANT: Return your analysis in this exact format:
    ```
    TYPE: [KNOWLEDGE_BASE|WEB_SEARCH|CODING|CONVERSATION]
    REASON: [Your explanation why]
    ```
  expected_output: >
    A structured analysis of the query type with exact format specified.
  agent: conversation_agent

knowledge_task:
  description: >
    IMPORTANT: First check the query analysis output in query_analysis.md.
    ONLY proceed if the analysis type is "KNOWLEDGE_BASE", otherwise return "SKIP: Not a knowledge base query".
    
    If proceeding:
    1. Use the directory tool to list available files
    2. Use the file tool to read relevant files, especially customers-100.csv
    3. Search for information about: {topic}
    4. Return ONLY information found in the knowledge base
    
    IMPORTANT: For customer queries:
    - Always check customers-100.csv first
    - Look for exact and partial name matches
    - Return all relevant customer information found
  expected_output: >
    Either the found information from knowledge base or skip message if not applicable.
  agent: knowledge_agent

search_task:
  description: >
    IMPORTANT: First check the query analysis output in query_analysis.md.
    ONLY proceed if the analysis type is "WEB_SEARCH" AND the knowledge task returned no results.
    Return "SKIP: Not a web search query" if either:
    - Analysis type is not WEB_SEARCH
    - Knowledge task found relevant information
    
    If proceeding:
    1. Use the SerperDev search tool to find current information
    2. Use the website tool to get more details if needed
    3. Format results with sources
  expected_output: >
    Either web search results with sources, or skip message if not applicable.
  agent: search_agent

conversation_task:
  description: >
    IMPORTANT: For KNOWLEDGE_BASE queries:
    1. Check knowledge_output.md
    2. If customer information is found, return it EXACTLY as found
    3. Do not modify or reformat the information
    4. Do not add any additional text or context
    5. Only if no information is found, treat as conversation
    
    For other query types:
    1. For WEB_SEARCH:
       - First check knowledge_output.md for local info
       - If no local info, check search_output.md
       - Format results with sources
    
    2. For CODING:
       - Provide technical response
       - Use examples when possible
    
    3. For CONVERSATION:
       - Respond naturally and engagingly
       - No need to search or check files
    
    Query: {topic}
  expected_output: >
    For KNOWLEDGE_BASE: The exact customer information without any modifications
    For WEB_SEARCH: Search results with sources
    For CODING: Technical explanation with examples
    For CONVERSATION: Natural dialogue response
  agent: conversation_agent

